### ISSUE TITLE
Error when running : TypeError [ERR_INVALID_CALLBACK]: Callback must be a function

### ISSUE THREAD

**Issue by fiftoine** [ember-cli/ember-modules-codemod#103]
Hi, When I'm running codemod on a recently updated version of ember (3.5.1), I get this error : 
```
Skipping path addon-test-support which does not exist.
Skipping path lib which does not exist.
Skipping path test-support which does not exist.
Processing 487 files...
Spawning 7 workers...
Sending 50 files to free worker...
Sending 50 files to free worker...
Sending 50 files to free worker...
Sending 50 files to free worker...
Sending 50 files to free worker...
Sending 50 files to free worker...
Sending 50 files to free worker...
Sending 50 files to free worker...
Sending 50 files to free worker...
Sending 37 files to free worker...
All done.
Results:
0 errors
486 unmodified
1 skipped
0 ok
Time elapsed: 3.353seconds
fs.js:137
    throw new ERR_INVALID_CALLBACK();
    ^

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at makeCallback (fs.js:137:11)
    at Object.unlink (fs.js:936:14)
    at logs.forEach.log (/usr/local/lib/node_modules/ember-modules-codemod/bin/ember-modules-codemod.js:87:10)
    at Array.forEach (<anonymous>)
    at glob (/usr/local/lib/node_modules/ember-modules-codemod/bin/ember-modules-codemod.js:71:10)
    at f (/usr/local/lib/node_modules/ember-modules-codemod/node_modules/once/once.js:25:25)
    at Glob.<anonymous> (/usr/local/lib/node_modules/ember-modules-codemod/node_modules/glob/glob.js:151:7)
    at Glob.emit (events.js:182:13)
    at Glob._finish (/usr/local/lib/node_modules/ember-modules-codemod/node_modules/glob/glob.js:197:8)
    at done (/usr/local/lib/node_modules/ember-modules-codemod/node_modules/glob/glob.js:182:14)
```

Setup:
```
ember-cli: 3.5.1
node: 10.13.0
os: darwin x64
ember-modules-codemod: 0.3.0
```

**Comment by rameramwe** [comment]
I'm also facing the same issue! any updates? is it actually important? cause for me it actually says 94 ok and no errors ... so maybe it's trivial...

**Comment by rinoldsimon** [comment]
seeing same issue in 
ember-cli - 3.7.1
ember-data - 3.7.0
node - 10.15.0

**Comment by rwjblue** [comment]
Should be fixed by https://github.com/ember-cli/ember-modules-codemod/pull/112

**Comment by BryanCrotaz** [comment]
I'm seeing this in Node 12.16.1 with ember 3.17.0
