### ISSUE TITLE
Doesn't work on Windows

### ISSUE THREAD

**Issue by vlascik** [ember-cli/ember-modules-codemod#13]
```
Error: spawn UNKNOWN
    at exports._errnoException (util.js:1036:11)
    at ChildProcess.spawn (internal/child_process.js:313:11)
    at exports.spawn (child_process.js:380:9)
    at Object.<anonymous> (D:\npm\node_modules\ember-modules-codemod\bin\ember-modules-codemod.js:24:19)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
```

**Comment by rwjblue** [comment]
I believe that this should be working properly now.  Happy to reopen if folks are still having issues.

**Comment by vlascik** [comment]
Nope, still the same error with 0.2.0.

**Comment by rwjblue** [comment]
Sorry about that.  Reopening...

**Comment by rwjblue** [comment]
We need to refactor [this code](https://github.com/ember-cli/ember-modules-codemod/blob/b919039c8d1cefbb0694dfcf08bed13db000e021/bin/ember-modules-codemod.js#L24) away from using `spawn` directly, and instead use something like `execa` (which has some additional built in capabilities with windows)...

**Comment by johnunclesam** [comment]
Any news on this?

**Comment by johnunclesam** [comment]
Ok. I fixed this. I'll pull request in one minute.
